name: Publish To PyPI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
   Task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        pip install -U pip
        pip install -r requirements.txt
    - name: Check commit message
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        if [[ "${COMMIT_MSG}" == publish:* ]]; then
          echo "Skipping publish due to commit message."
          echo "skip_publish=true" >> $GITHUB_ENV
        else
          echo "skip_publish=false" >> $GITHUB_ENV
        fi
    - name: Publish to PyPI
      if: env.skip_publish == 'false'
      run: |
        VERSION=$(grep VERSION setup.py | grep -oP "'\K[0-9]+\.[0-9]+\.[0-9]+")
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch + 1))
        NEW_VERSION="$major.$minor.$patch"
        sed -i "s/VERSION = '$VERSION'/VERSION = '$NEW_VERSION'/" setup.py
        python setup.py sdist build
        twine upload dist/* -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_M2N_TOKEN }}
    - name: Git Commit
      if: env.skip_publish == 'false'
      run: |
        git config --local user.email "action-publish@github.com"
        git config --local user.name "GitHub Action Publish"
        git add .
        git commit -m "publish: version $NEW_VERSION"
    - name: Push changes
      if: env.skip_publish == 'false'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
